// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQQxrzWfFTtbKN_M2MB2TYs_U9cCog1K4',
    appId: '1:484073222101:web:1ce5df6a60e34b95b9575c',
    messagingSenderId: '484073222101',
    projectId: 'mychat-1a8ad',
    authDomain: 'mychat-1a8ad.firebaseapp.com',
    storageBucket: 'mychat-1a8ad.firebasestorage.app',
    measurementId: 'G-NWRQK3NMWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsyltNFSlDR1qeRfiJLrwA4Rxzom3yZEE',
    appId: '1:484073222101:android:6527fecb8afc6794b9575c',
    messagingSenderId: '484073222101',
    projectId: 'mychat-1a8ad',
    storageBucket: 'mychat-1a8ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdwWEdM08mblZnrx2FZ_sXagCg1i06EDU',
    appId: '1:484073222101:ios:88c7b3c8bd58190fb9575c',
    messagingSenderId: '484073222101',
    projectId: 'mychat-1a8ad',
    storageBucket: 'mychat-1a8ad.firebasestorage.app',
    iosBundleId: 'com.example.imApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdwWEdM08mblZnrx2FZ_sXagCg1i06EDU',
    appId: '1:484073222101:ios:88c7b3c8bd58190fb9575c',
    messagingSenderId: '484073222101',
    projectId: 'mychat-1a8ad',
    storageBucket: 'mychat-1a8ad.firebasestorage.app',
    iosBundleId: 'com.example.imApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQQxrzWfFTtbKN_M2MB2TYs_U9cCog1K4',
    appId: '1:484073222101:web:ef625709fad63faab9575c',
    messagingSenderId: '484073222101',
    projectId: 'mychat-1a8ad',
    authDomain: 'mychat-1a8ad.firebaseapp.com',
    storageBucket: 'mychat-1a8ad.firebasestorage.app',
    measurementId: 'G-1516G9Z6Q0',
  );
}
